server:
    port: 9191
spring:
    application:
        name: SpringBootRabbitMQListener
#spring.jpa.hibernate.ddl-auto=create
    datasource:
        url: jdbc:mysql://kubernetes2.local:303306/test
        username: root
        password: secret
#spring.datasource.driver-class-name=Driver
# Allows Hibernate to generate SQL optimized for a particular DBMS
    jpa:
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
            hibernate.show_sql: true
    rabbitmq:
        host:tools.local
        password:guest
        port:5672
    zipkin:
        baseUrl: http://mesos1.local:7777
    sleuth:
        sampler:
            percentage: 1
    cloud:
        stream:
            defaultBinder: kafka        
            bindings:
                worksChannel:
                  destination: my-topic
                  content-type: application/json
                  binder: kafka
            binders:
                rabbit1:
                    type: rabbit
                    environment:
                        spring:
                            rabbitmq:
                                host: rabbitmq
                                port: 5672
                                username: guest
                                password: guest
                                virtual-host: /
                kafka:
                    type: kafka
                    environment:
                        spring:
                            cloud:
                                stream:
                                    kafka:
                                        binder:
                                            brokers: hdp1.local:6667,hdp2.local:6667,hdp3.local:6667
            kafka:
                binder:
                    brokers: hdp1.local,hdp2.local,hdp3.local
                    zkNodes: hdp1.local,hdp2.local,hdp3.local
                    defaultZkPort: 2181
                    defaultBrokerPort: 9092                                